In [1]:
# a = [[1,2],[3,4]]
# a[1]
import torch
weights = torch.normal(0,1,(2,1))
data =  torch.normal(0,1,(10,2))
print(torch.mm(data,weights).mean())
print(torch.rand(1))

tensor(-0.1791)
tensor([0.9035])


In [5]:
import torch
# a = torch.tensor([1.1,2.],requires_grad=True)
# b = torch.clamp(a,2)
# b
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[1,2],[3,3]])
torch.mm(b,a)

tensor([[ 7, 10],
        [12, 18]])

In [2]:
import torch
print(torch.rand(3,4))
print(torch.rand([3,4]))

tensor([[0.4925, 0.0414, 0.3014, 0.7962],
        [0.6223, 0.8671, 0.5535, 0.6170],
        [0.4589, 0.6550, 0.8416, 0.8485]])
tensor([[0.9355, 0.6209, 0.3183, 0.2531],
        [0.8520, 0.9030, 0.3602, 0.6283],
        [0.0567, 0.0652, 0.2043, 0.8270]])
