In [17]:
import torch
import torch.nn.functional as F
a = torch.tensor([[1,2,3],[3,4,7]])
partition = a.sum(dim=1, keepdim=True)
print(a/partition)
print(F.one_hot(torch.tensor([7])))
print(a.size(1))
print(a - torch.max(a))

tensor([[0.1667, 0.3333, 0.5000],
        [0.2143, 0.2857, 0.5000]])
tensor([[0, 0, 0, 0, 0, 0, 0, 1]])
3
tensor([[-6, -5, -4],
        [-4, -3,  0]])
